// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.64.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<Sudoku> sudoku({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_sudoku(port_),
      parseSuccessData: _wire2api_sudoku,
      constMeta: kSudokuConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSudokuConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "sudoku",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  CellArray81 _wire2api_Cell_array_81(dynamic raw) {
    return CellArray81((raw as List<dynamic>).map(_wire2api_cell).toList());
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  Digit _wire2api_box_autoadd_digit(dynamic raw) {
    return _wire2api_digit(raw);
  }

  Candidates _wire2api_candidates(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Candidates(
      field0: _wire2api_usize(arr[0]),
    );
  }

  Cell _wire2api_cell(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Cell(
      coord: _wire2api_coord(arr[0]),
      digit: _wire2api_opt_box_autoadd_digit(arr[1]),
      isGiven: _wire2api_bool(arr[2]),
      candidates: _wire2api_candidates(arr[3]),
    );
  }

  Coord _wire2api_coord(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Coord(
      field0: _wire2api_usize(arr[0]),
      field1: _wire2api_usize(arr[1]),
    );
  }

  Digit _wire2api_digit(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Digit(
      field0: _wire2api_u8(arr[0]),
    );
  }

  List<Cell> _wire2api_list_cell(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_cell).toList();
  }

  Digit? _wire2api_opt_box_autoadd_digit(dynamic raw) {
    return raw == null ? null : _wire2api_box_autoadd_digit(raw);
  }

  Sudoku _wire2api_sudoku(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Sudoku(
      field0: _wire2api_Cell_array_81(arr[0]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  int _wire2api_usize(dynamic raw) {
    return castInt(raw);
  }
}

// Section: api2wire

// Section: finalizer
