// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.64.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'package:collection/collection.dart';

abstract class Native {
  Future<Sudoku> sudoku({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSudokuConstMeta;
}

class CellArray81 extends NonGrowableListView<Cell> {
  static const arraySize = 81;
  CellArray81(List<Cell> inner)
      : assert(inner.length == arraySize),
        super(inner);
  CellArray81.unchecked(List<Cell> inner) : super(inner);
  CellArray81.init(Cell fill) : super(List<Cell>.filled(arraySize, fill));
}

class Candidates {
  final int field0;

  Candidates({
    required this.field0,
  });
}

class Cell {
  final Coord coord;
  final Digit? digit;
  final bool isGiven;
  final Candidates candidates;

  Cell({
    required this.coord,
    this.digit,
    required this.isGiven,
    required this.candidates,
  });
}

class Coord {
  final int field0;
  final int field1;

  Coord({
    required this.field0,
    required this.field1,
  });
}

class Digit {
  final int field0;

  Digit({
    required this.field0,
  });
}

class Sudoku {
  final CellArray81 field0;

  Sudoku({
    required this.field0,
  });
}
